apiVersion: v1
name: wavefront
description: Wavefront Kubernetes collector
appVersion: 0.9.8
version: 1.0.0
keywords:
- metric
- monitoring
- observability
- alerting
home: https://www.wavefront.com
sources:
- https://github.com/wavefrontHQ/wavefront-kubernetes-collector
- https://github.com/wavefrontHQ/java/tree/master/proxy
